export const PRODUCT_LIST_REQUEST = "PPRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PPRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PPRODUCT_LIST_FAIL"

export const PRODUCT_DETAILS_REQUEST = "PPRODUCT_DETAILS_REQUEST"
export const PRODUCT_DETAILS_SUCCESS = "PPRODUCT_DETAILS_SUCCESS"
export const PRODUCT_DETAILS_FAIL = "PPRODUCT_DETAILS_FAIL"
